#Desafio 004
n = input('Digite algo: ')
print('O seu tipo é {}'.format(type(n)))
print('É numero? ', n.isnumeric())
print('É uma letra maiuscula? ', n.isupper())
print('É uma letra minuscula? ', n.islower())
print('É uma letra alfabético? ', n.isalpha())
print('É numero decimal? ', n.isdecimal())
print('Só possui espaços? ', n.isspace())
print('Está capitalizado ou seja Possui maiusculas e minusculas?', n.istitle())
